# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:

    # --------------------------------------------------------------------------------
    # DATABASES
    # --------------------------------------------------------------------------------

    # MariaDB
    mariadb:
      container_name: ${MARIA_CONTAINER_NAME}
      image: ${MARIA_IMAGE_NAME}
      working_dir: /application
      restart: always
      networks:
        - labnet
      volumes:
        - maria_data:/var/lib/mysql
        - ./initdb/database.db.sql:/docker-entrypoint-initdb.d/database.sql
      environment:
        - MYSQL_ROOT_PASSWORD=${MARIA_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MARIA_NAME}
        - MYSQL_USER=${MARIA_USER}
        - MYSQL_PASSWORD=${MARIA_PASSWORD}
      ports:
        - "3002:${MARIA_PORT}"

# ======================================================================================================================
# NETWORKS
# ======================================================================================================================

networks:
  labnet:
    driver: bridge

# ======================================================================================================================
# VOLUMES
# ======================================================================================================================

volumes:       
  maria_data: