# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
        - labnet
    environment:
      - DB_HOST=${MARIA_HOST}
      - DB_USER=${MARIA_USER}
      - DB_PASSWORD=${MARIA_PASSWORD}
      - DB_NAME=${MARIA_NAME}

networks:
  labnet:
    driver: bridge